# Main configuration for the Welcome plugin
settings:
  # This is the time after the player's first connection during which the welcome message will be sent.
  # After this time, no rewards will be given.
  welcome-delay: 11000 #in second
  # Type of welcome message sent (global, public or private),
  # global sends a message as a broadcast,
  # player the player executing the command sends a public message
  # and private allows a message to be sent only to the newcomer.
  welcome-message-type: global  # Options: global, player or private
  # Reward configuration
  rewards:
    # Enable or disable rewards
    enabled: true
    # List of commands to execute for rewards
    commands:
      - "eco give %player_name% 1000"
      - "give %player_name% diamond 2"