welcome-delay: 1200 #Time in seconds, after this delay the player can no longer greet the player who joined
no-player:
  message: "<yellow><bold>Server<reset> <gold>No player to greet"
no-permission:
  message: "<yellow><bold>Server<reset> <dark_red>Unknown command..."
new-player:
  message: "<yellow><bold>Server<reset> <gold>Welcome %player_name% /welcome"
invalid-player:
  message: "<yellow><bold>Server<reset> <gold>You cannot welcome yourself."
already-send:
  message: "<yellow><bold>Server<reset> <gold>You have already welcomed %player_name%"
welcome-send:
  message: "<yellow><bold>Server<reset> <gold>You welcomed %player_name%"
welcome-format:
  message: "<yellow><bold>Server<reset> <gold>%player_name% <green>welcomed you."
reload:
  message: "<yellow><bold>Server<reset> <gold>Reload complete"


rewards:
  enabled: true
  commands:
    - "broadcast reward 1 %player_name%"
    - "broadcast reward 2"
    - "broadcast reward 3"
