# Main configuration for the Welcome plugin
settings:
  # This is the time after the player's first connection during which the welcome message will be sent.
  # After this time, no rewards will be given.
  welcome-delay: 11000 #in second
  # Type d'envoi du message de bienvenue (global ou privé)
  welcome-message-type: global  # Options : global, privé
  # Reward configuration
  rewards:
    # Enable or disable rewards
    enabled: true
    # List of commands to execute for rewards
    commands:
      - "eco give %player_name% 1000"
      - "give %player_name% diamond 2"