no-player:
  message: "<yellow><bold>Serveur<reset> <gold>Aucun joueur à qui souhaiter la bienvenue"
no-permission:
  message: "<yellow><bold>Serveur<reset> <dark_red> Commande inconnue..."
new-player:
  message: "<yellow><bold>Serveur<reset> <gold>Souhaitez la bienvenue à %player_name% /bvn"
invalid-player:
  message: "<yellow><bold>Serveur<reset> <gold>Vous ne pouvez pas souhaiter la bienvenue à vous-même."
already-send:
  message: "<yellow><bold>Serveur<reset> <gold>Vous avez déjà souhaité la bienvenue à %player_name%"
welcome-send:
  message: "<yellow><bold>Serveur<reset> <gold>Vous avez souhaité bienvenue à %player_name%"
welcome-format:
  message: "<yellow><bold>Serveur<reset> <gold>%player_name% <green>vous a souhaité la bienvenue."

rewards:
  enabled: true
  commands:
    - "broadcast reward 1"
    - "broadcast reward 2"
    - "broadcast reward 3"

