name: Welcome
version: '1.7.2'
main: fr.jesuistrolls.welcome.Welcome
api-version: "1.16"
depend:
  - Vault
  - PlaceholderAPI
commands:
  welcome:
    aliases: [bienvenue, wlc, bvn]
permissions:
  welcome.admin:
    description: Gives access to all Welcome admin commands
    default: op
  welcome.command.welcome:
    description: Welcome commands
    default: true
  welcome.join:
    description: -in check
    default: false
libraries:
  - net.kyori:adventure-api:4.15.0
  - net.kyori:adventure-platform-bukkit:4.3.2
  - net.kyori:adventure-text-minimessage:4.15.0