name: Welcome
version: '${project.version}'
main: fr.jesuistrolls.welcome.Welcome
api-version: '1.20'
commands:
  bvn:
    aliases: [bienvenue, wlc, welcome]
libraries:
  - net.kyori:adventure-api:4.15.0
  - net.kyori:adventure-platform-bukkit:4.3.2
  - net.kyori:adventure-text-minimessage:4.15.0